import pygame

def load_images():
    background_image = pygame.image.load('./assets/bricktetris/images/tetris_background.jpg').convert()
    return background_image

# screen positioning
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
LEFT_RIGHT_MARGIN = 150
MAIN_SCREEN_TOP_DOWN_MARGIN = 50
BETWEEN_SCREENS_MARGIN = 100
MAIN_SCREEN_WIDTH = SCREEN_WIDTH // 3
MAIN_SCREEN_HEIGHT = SCREEN_HEIGHT - 2 * MAIN_SCREEN_TOP_DOWN_MARGIN
NEXT_SCREEN_TOP_MARGIN = MAIN_SCREEN_TOP_DOWN_MARGIN + 50
INFO_SCREEN_DOWN_MARGIN = MAIN_SCREEN_TOP_DOWN_MARGIN + 50
MAIN_SCREEN_Y = MAIN_SCREEN_TOP_DOWN_MARGIN
NEXT_SCREEN_Y = NEXT_SCREEN_TOP_MARGIN
INFO_SCREEN_HEIGHT = SCREEN_HEIGHT // 2 - INFO_SCREEN_DOWN_MARGIN
INFO_SCREEN_Y = SCREEN_HEIGHT - INFO_SCREEN_DOWN_MARGIN - INFO_SCREEN_HEIGHT
INFO_SCREEN_WIDTH = MAIN_SCREEN_WIDTH - LEFT_RIGHT_MARGIN - BETWEEN_SCREENS_MARGIN
NEXT_SCREEN_WIDTH = INFO_SCREEN_WIDTH
NEXT_SCREEN_HEIGHT = INFO_SCREEN_HEIGHT
MAIN_SCREEN_X = SCREEN_WIDTH // 3
INFO_SCREEN_X = LEFT_RIGHT_MARGIN
NEXT_SCREEN_X = SCREEN_WIDTH - LEFT_RIGHT_MARGIN - NEXT_SCREEN_WIDTH

LIGHT_BLUE = (137, 207, 240)
DARK_BLUE = (0, 0, 255)