import pygame

# screen settings
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
SCROLL = 200
HOVER = SCROLL // 10
FPS = 60

# playable area stretch
STRETCH = 100

# container area
CONTAINER_AREA_TOP_X = SCREEN_WIDTH // 3 - STRETCH
CONTAINER_AREA_TOP_Y = 0

# background settings
BACKGROUND_WIDTH_TOTAL = SCREEN_WIDTH // 3 + STRETCH * 2
PILLAR_WIDTH = 160
PILLAR_HEIGHT = SCREEN_HEIGHT
PLAYABLE_AREA_WIDTH = BACKGROUND_WIDTH_TOTAL - (2 * PILLAR_WIDTH)

# platform settings
ON_SCREEN_NUMBER_OF_PLATFORMS = 5
PLATFORM_WIDTH = 160
PLATFORM_HEIGHT = 30
PLATFORM_INIT_Y = SCREEN_HEIGHT - 150
LEFT_PLATFORM_X = CONTAINER_AREA_TOP_X + PILLAR_WIDTH
RIGHT_PLATFORM_X = CONTAINER_AREA_TOP_X + PILLAR_WIDTH + PLAYABLE_AREA_WIDTH - PLATFORM_WIDTH
PLATFORM_Y_GAP = SCROLL
UPPER_PLATFORM_Y = PLATFORM_INIT_Y - (ON_SCREEN_NUMBER_OF_PLATFORMS - 1) * PLATFORM_Y_GAP
SHAKE_INTENSITIY = 3
INIT_PLATFORM_SHAKE_DURATION = 1000
MIN_PLATFORM_SHAKE_DURATION = 100

# player
PLAYER_WIDTH = 50
PLAYER_HEIGHT = 50
PLAYER_ON_LEFT_PLATFORM_X = LEFT_PLATFORM_X + PLATFORM_WIDTH // 2 - PLAYER_WIDTH // 2
PLAYER_ON_RIGHT_PLATFORM_X = RIGHT_PLATFORM_X + PLATFORM_WIDTH // 2 - PLAYER_WIDTH // 2

# colors
SKY_BLUE = (135, 206, 235)
UNDERGROUND_BROWN = (139, 69, 19)
FOREST_GREEN = (34, 139, 34)