import pygame

# screen settings
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 60

# very important variable
STRETCH = 100

# container area
CONTAINER_AREA_TOP_X = SCREEN_WIDTH // 3 - STRETCH
CONTAINER_AREA_TOP_Y = 0

# background settings
BACKGROUND_WIDTH_TOTAL = SCREEN_WIDTH // 3 + STRETCH * 2
PILLAR_WIDTH = 160
PILLAR_HEIGHT = SCREEN_HEIGHT
PLAYABLE_AREA_WIDTH = BACKGROUND_WIDTH_TOTAL - (2 * PILLAR_WIDTH)

# platform settings
PLATFORM_WIDTH = 160
PLATFORM_HEIGHT = 30
PLATFORM_INIT_Y = SCREEN_HEIGHT - 150
LEFT_PLATFORM_X = CONTAINER_AREA_TOP_X + PILLAR_WIDTH
RIGHT_PLATFORM_X = CONTAINER_AREA_TOP_X + PILLAR_WIDTH + PLAYABLE_AREA_WIDTH - PLATFORM_WIDTH

# colors
SKY_BLUE = (135, 206, 235)
UNDERGROUND_BROWN = (139, 69, 19)
FOREST_GREEN = (34, 139, 34)
